enum FilterType {
  region_overview,
  architecture,
  religion,
  building_type,
}

enum CategoryType {
  // Building Types
  marketplace,
  courthouse,
  hospital,
  institution,
  place_of_worship,
  heritage,
  zoo,
  museum,
  commercial,
  government,
  residential,
  library,
  fountain,
  theatre,
  pagoda,
  park,
  reservoir,
  landmark,
  prison,

  // Architectural Styles
  french,
  modernism,
  east_asia,
  contemporary,
  baroque,
  rococo,
  vietnamese,
  chinese,
  romanesque,
  gothic,
  renaissance,
  neo_romanesque,
  neo_baroque,
  indochine,
  art_deco,
  hindu,
  khmer,
  islam,
  flamboyant,
  beaux_arts,
  brutalism,
  korean,
  art_nouveau,

  // Religious Categories
  taoist,
  chinese_folk,
  buddhist,
  christian,
  hinduism,
  vietnamese_folk,
  muslim,
}

Map<FilterType, List<CategoryType>> filterCategoryMapping = {
  FilterType.architecture: [
    CategoryType.french,
    CategoryType.modernism,
    CategoryType.east_asia,
    CategoryType.contemporary,
    CategoryType.baroque,
    CategoryType.rococo,
    CategoryType.vietnamese,
    CategoryType.chinese,
    CategoryType.romanesque,
    CategoryType.gothic,
    CategoryType.renaissance,
    CategoryType.neo_romanesque,
    CategoryType.neo_baroque,
    CategoryType.indochine,
    CategoryType.art_deco,
    CategoryType.hindu,
    CategoryType.khmer,
    CategoryType.islam,
    CategoryType.flamboyant,
    CategoryType.beaux_arts,
    CategoryType.brutalism,
    CategoryType.korean,
    CategoryType.art_nouveau,
  ],
  FilterType.religion: [
    CategoryType.taoist,
    CategoryType.chinese_folk,
    CategoryType.buddhist,
    CategoryType.christian,
    CategoryType.hinduism,
    CategoryType.vietnamese_folk,
    CategoryType.muslim,
  ],
  FilterType.building_type: [
    CategoryType.marketplace,
    CategoryType.courthouse,
    CategoryType.hospital,
    CategoryType.institution,
    CategoryType.place_of_worship,
    CategoryType.heritage,
    CategoryType.zoo,
    CategoryType.museum,
    CategoryType.commercial,
    CategoryType.government,
    CategoryType.residential,
    CategoryType.library,
    CategoryType.fountain,
    CategoryType.theatre,
    CategoryType.pagoda,
    CategoryType.park,
    CategoryType.reservoir,
    CategoryType.landmark,
    CategoryType.prison,
  ],
};
