enum FilterType {
  regionOverview,
  architecture,
  religion,
  buildingType,
}

enum CategoryType {
  // Building Types
  marketplace,
  communityCentre,
  courthouse,
  hospital,
  mortuary,
  institution,
  tomb,
  placeOfWorship,
  heritage,
  zoo,
  museum,
  commercial,
  government,
  residential,
  library,
  fountain,
  theatre,
  pagoda,
  park,
  reservoir,
  landmark,
  prison,

  // Architectural Styles
  french,
  modernism,
  eastAsia,
  contemporary,
  baroque,
  rococo,
  vietnamese,
  chinese,
  romanesque,
  gothic,
  renaissance,
  neoRomanesque,
  neoBaroque,
  indochine,
  artDeco,
  hindu,
  khmer,
  islam,
  flamboyant,
  beauxArts,
  brutalism,
  korean,
  artNouveau,

  // Religious Categories
  taoist,
  chineseFolk,
  buddhist,
  christian,
  hinduism,
  vietnameseFolk,
  muslim,
}

Map<FilterType, List<CategoryType>> filterCategoryMapping = {
  FilterType.architecture: [
    CategoryType.french,
    CategoryType.modernism,
    CategoryType.eastAsia,
    CategoryType.contemporary,
    CategoryType.baroque,
    CategoryType.rococo,
    CategoryType.vietnamese,
    CategoryType.chinese,
    CategoryType.romanesque,
    CategoryType.gothic,
    CategoryType.renaissance,
    CategoryType.neoRomanesque,
    CategoryType.neoBaroque,
    CategoryType.indochine,
    CategoryType.artDeco,
    CategoryType.hindu,
    CategoryType.khmer,
    CategoryType.islam,
    CategoryType.flamboyant,
    CategoryType.beauxArts,
    CategoryType.brutalism,
    CategoryType.korean,
    CategoryType.artNouveau,
  ],
  FilterType.religion: [
    CategoryType.taoist,
    CategoryType.chineseFolk,
    CategoryType.buddhist,
    CategoryType.christian,
    CategoryType.hinduism,
    CategoryType.vietnameseFolk,
    CategoryType.muslim,
  ],
  FilterType.buildingType: [
    CategoryType.marketplace,
    CategoryType.communityCentre,
    CategoryType.courthouse,
    CategoryType.hospital,
    CategoryType.mortuary,
    CategoryType.institution,
    CategoryType.tomb,
    CategoryType.placeOfWorship,
    CategoryType.heritage,
    CategoryType.zoo,
    CategoryType.museum,
    CategoryType.commercial,
    CategoryType.government,
    CategoryType.residential,
    CategoryType.library,
    CategoryType.fountain,
    CategoryType.theatre,
    CategoryType.pagoda,
    CategoryType.park,
    CategoryType.reservoir,
    CategoryType.landmark,
    CategoryType.prison,
  ],
};
